version: '3.9'

services:
  httpd:
    container_name: httpd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../scripts:/scripts
    ports:
      - "9090:80"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - lab

networks:
  lab: